---
# handlers file for nfs-client
- name: reload mount
  mount:
    fstype: nfs
    name: "{{ item.path }}"
    opts: "{{ item.opts | default(nfs_mount_opts) }}"
    src: "{{ item.location }}"
    dump: "{{ item.dump | default(omit) }}"
    passno: "{{ item.passno | default(omit) }}"
    state: "{{ item.state | default( 'mounted' ) }}"
  with_items: "{{ nfs_share_mounts }}"
