---
# tasks file for nfs-client
- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=present

- name: firewalld permits rpc-bind service
  firewalld:
    service: rpc-bind
    permanent: true
    state: enabled
    immediate: yes

- name: firewalld permits nfs service
  firewalld:
    service: nfs
    permanent: true
    state: enabled
    immediate: yes

- name: Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: "{{ nfs_rpcbind_state }}"
    enabled: "{{ nfs_rpcbind_enabled }}"

- name: Ensure nfs-server is running and enabled
  service:
    name: nfs-server
    state: started
    enabled: true

- name: Ensure nfs-lock is running and enabled
  service:
    name: nfs-lock
    state: started
    enabled: true

- name: Ensure nfs-idmap is running and enabled
  service:
    name: nfs-idmap
    state: started
    enabled: true

- name: Ensure directories exist
  file: 'path="{{ item.path }}" state=directory'
  with_items: "{{ nfs_share_mounts }}"

- name: Update fstab file
  lineinfile:
    path: /etc/fstab
    regexp: '^{{ item.location }}'
    line: "{{ nfs_fstab }}"
  with_items: "{{ nfs_share_mounts }}"
  notify: reload mount

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"

- name: Create a sample file in /clientshare directory
  shell: |
    echo 'This is line one in sample file.
    This is line two.
    This is line three' > /clientshare/sample_share.txt

